services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "443:443"
      - "80:80"  # Exposing HTTP for Let's Encrypt challenges
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Ensure nginx.conf is mounted
      - ./nginx/freesectools.conf:/etc/nginx/conf.d/default.conf  # Mount the site configuration
      - ./nginx/live/freesectools.com:/etc/nginx/live/freesectools.com  # Mount SSL certificates
      - ./app/static:/var/www/html/freesectools.com/app/static  # Static files mount
    depends_on:
      - web  # Make sure Flask app starts before Nginx
    networks:
      - app-network

  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 app:app  # Adjust the Flask app entry point
    volumes:
      - ./app:/app
    expose:
      - "8000"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    expose:
      - "6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
