from flask import Blueprint, render_template
from modules.outsiders.new_cve import CyberCVEFetcher
import random

home_bp = Blueprint("home", __name__)


TeaTimeTips = [
    "Over 80% of breaches involve brute force or the use of lost or stolen credentials. Strong, unique passwords are your first line of defense.",
    "The average time to identify a breach in 2023 was 212 days. Early detection can save companies millions in damage control.",
    "Cybercrime costs the global economy over $1 trillion annually, more than the GDP of many countries.",
    "43% of cyber attacks target small businesses. Yet, 83% of small businesses are not financially prepared to recover from a cyber attack.",
    "End-to-end encryption ensures that only the communicating users can read the messages. Not even service providers can access the encrypted content.",
    "Public Wi-Fi networks are notorious for being insecure. Hackers can easily intercept data shared over these networks unless it is encrypted.",
    "Phishing attacks have become the most common cyber threat, with around 1 in every 99 emails being a phishing attempt.",
    "Multi-factor authentication (MFA) can block up to 99.9% of automated cyber attacks. It is one of the simplest ways to secure your accounts.",
    "Ransomware attacks have increased by over 150% in the past two years, with the average ransom demand exceeding $100,000.",
    "Zero-day vulnerabilities are unknown to the software vendor and can remain unpatched for months or even years, posing a significant risk.",
    "The most common password in the world is still '123456.' It is used by millions despite being one of the least secure passwords imaginable.",
    "Ethical hacking involves testing your systems' defenses. Many companies hire ethical hackers to find vulnerabilities before malicious hackers do.",
    "IoT (Internet of Things) devices are a growing target for hackers. Weak security on these devices can provide a backdoor into entire networks.",
    "'Air-gapped' computers, which are physically isolated from unsecured networks, are considered highly secure. However, even they are not immune to sophisticated attacks.",
    "In 2024, it is estimated that a hacker attack occurs every 39 seconds, affecting one in three people annually.",
    "Advanced Persistent Threats (APTs) are long-term, targeted attacks on specific entities. APTs often remain undetected for extended periods, causing significant damage.",
    "DNSSEC (Domain Name System Security Extensions) helps protect against DNS spoofing and cache poisoning attacks by adding cryptographic signatures to DNS data.",
    "'Social engineering' attacks exploit human psychology rather than technical vulnerabilities, making them extremely effective and hard to defend against.",
    "Cloud misconfigurations were responsible for 45% of data breaches in 2023, highlighting the importance of secure cloud practices.",
    "Supply chain attacks have been on the rise, with attackers compromising software updates to inject malware into target systems.",
    "Quantum computing poses a potential future threat to current encryption standards, necessitating the development of quantum-resistant cryptography.",
    "Cybersecurity skills are in high demand, with a global shortage of over 3 million cybersecurity professionals reported in 2024.",
    "Over 90% of successful cyber attacks start with a phishing email. Always verify the sender before clicking on links or downloading attachments.",
    "By 2025, it is estimated that cybercrime will cost the world $10.5 trillion annually, up from $3 trillion in 2015.",
    "The 'man-in-the-middle' attack is one of the most common forms of data interception, where attackers secretly relay and alter communication between two parties.",
    "A 2024 study found that 60% of companies go out of business within six months of a major cyber attack.",
    "Biometric authentication methods like fingerprint and facial recognition are more secure than traditional passwords but are not entirely foolproof.",
    "Cyber insurance is becoming an essential part of risk management for businesses, covering costs associated with data breaches and cyber attacks.",
    "The 'Internet of Behavior' (IoB) is an emerging trend where user behavior data is collected and analyzed, raising new privacy and security concerns.",
    "In 2023, 'Deepfake' technology has become a significant cybersecurity threat, used in sophisticated phishing and disinformation campaigns.",
    "Botnets are networks of compromised devices used to launch large-scale attacks. In 2024, botnet attacks have become more advanced and harder to detect.",
    "Over 50% of data breaches in 2023 were caused by human error, emphasizing the need for ongoing cybersecurity training.",
    "Social media platforms are increasingly being used for social engineering attacks. Be cautious about the information you share online.",
    "Security patches are critical. On average, it takes organizations 100 days to patch known vulnerabilities, leaving them open to exploits.",
    "Blockchain technology offers potential solutions for secure data transactions, but it is not immune to threats like the '51% attack.'",
    "Fileless malware, which resides in memory instead of being stored on disk, has been increasingly used in attacks to evade traditional antivirus software.",
    "AI and machine learning are being used to enhance cybersecurity defenses, but they are also being leveraged by attackers to create more sophisticated threats.",
    "A Virtual Private Network (VPN) can help secure your internet connection, especially when using public Wi-Fi networks.",
    "Ransomware as a Service (RaaS) has become a growing industry on the dark web, making it easier for non-experts to launch ransomware attacks.",
    "The Zero Trust security model operates on the principle of 'never trust, always verify,' reducing the risk of insider threats.",
    "Dark web monitoring services can help detect if your personal or company data has been compromised and is being sold online.",
    "Encryption is essential for data protection, but remember: if you lose the decryption key, you lose access to your data.",
    "DNS hijacking is a common attack where hackers redirect web traffic to malicious websites by altering DNS settings.",
    "Email spoofing allows attackers to send emails that appear to come from a trusted source. Always verify unexpected requests, even from familiar contacts.",
    "Data exfiltration is a method used by cybercriminals to extract sensitive data from an organization, often going unnoticed for months.",
    "Cybersecurity frameworks like NIST and ISO 27001 provide guidelines to help organizations implement effective security practices.",
    "The principle of 'least privilege' states that users should only have the minimum access necessary to perform their tasks, reducing the risk of insider threats.",
    "Password spraying is a brute-force attack where attackers try common passwords across many accounts, rather than targeting one account with multiple passwords.",
    "Distributed Denial of Service (DDoS) attacks flood a network or website with traffic to make it unavailable to users. DDoS protection is essential for high-traffic sites.",
    "The 'Cyber Kill Chain' is a model used to describe the stages of a cyber attack, helping organizations understand and defend against threats.",
    "Credential stuffing attacks use stolen usernames and passwords from data breaches to gain unauthorized access to accounts. Use unique passwords for each account.",
    "Sandboxing is a security mechanism used to test software in an isolated environment, preventing potentially harmful code from affecting the main system.",
    "Homoglyph attacks involve using visually similar characters to deceive users, such as replacing 'o' with '0' in URLs.",
    "Cybersecurity compliance regulations like GDPR, CCPA, and HIPAA mandate strict data protection standards to protect user privacy.",
    "The 'shadow IT' phenomenon occurs when employees use unauthorized software or devices, creating security risks for the organization.",
    "End-users are the weakest link in cybersecurity. Regular training and awareness programs are vital to reducing the risk of human error.",
    "Data minimization is a key privacy principle: collect only the data you need and keep it only as long as necessary.",
    "Keylogging malware records keystrokes on infected devices, often used to steal passwords and other sensitive information.",
    "Network segmentation divides a network into segments to limit the spread of malware and restrict access to sensitive data.",
    "A Security Operations Center (SOC) is a centralized unit that monitors and analyzes an organization’s security posture, detecting and responding to cyber threats.",
    "Identity and Access Management (IAM) solutions help manage user identities and control access to resources, reducing the risk of unauthorized access.",
    "Firmware updates are crucial for securing IoT and other devices. Outdated firmware can leave devices vulnerable to exploits.",
    "Malvertising involves injecting malicious ads into legitimate online advertising networks, leading users to malware-infected websites.",
    "Breach and attack simulation tools help organizations identify vulnerabilities by simulating real-world cyber attacks.",
    "Cyber threat intelligence (CTI) involves collecting and analyzing information about potential threats to better understand and defend against them.",
    "Data masking hides sensitive data by replacing it with fictional data, used to protect privacy while maintaining the usefulness of datasets.",
    "Machine identity management is crucial for securing communications between devices and applications, as machines outnumber humans on networks.",
    "Patch management tools help automate the process of updating software and systems, reducing the window of vulnerability to attacks.",
    "Red teaming is a simulated attack exercise where security professionals attempt to breach an organization’s defenses to identify weaknesses.",
    "Security Information and Event Management (SIEM) systems collect and analyze log data to identify potential security incidents in real time.",
    "Insider threats are among the most difficult to detect and prevent, often involving employees with legitimate access to sensitive information.",
    "Privileged Access Management (PAM) solutions secure, control, and monitor access to critical systems and data, reducing the risk of abuse by privileged users.",
    "In 2024, spear-phishing attacks are more targeted and sophisticated, often personalized to trick specific individuals into divulging sensitive information.",
    "Deep web and dark web are often confused. The deep web contains non-indexed, but generally harmless content, while the dark web hosts hidden illegal activities and requires special tools like Tor to access.",
    "Cybersecurity spending is expected to exceed $300 billion globally by 2026, driven by the rise in sophisticated cyber threats.",
    "More than 50% of organizations experienced some form of mobile malware attack in 2023. Mobile device security is just as crucial as desktop security.",
    "Biometric data, such as fingerprints, once compromised cannot be changed like passwords. This makes securing biometric data extremely important.",
    "In a survey, 78% of security professionals reported an increase in phishing attacks in 2023, with attackers using AI to make these attacks more convincing.",
    "The average ransomware downtime in 2023 was 21 days, causing significant disruption to businesses worldwide.",
    "USB drop attacks involve leaving infected USB drives in public places, hoping someone will plug them into their computer out of curiosity, thus spreading malware.",
    "Security headers, like Content Security Policy (CSP) and X-Content-Type-Options, help protect websites from a variety of attacks, including XSS and clickjacking.",
    "Data breaches are most commonly caused by stolen or weak passwords. Passwordless authentication methods are gaining traction as a more secure alternative.",
    "Hackers are now using 'voice phishing' or 'vishing' to trick individuals into revealing personal information over the phone.",
    "The 'EternalBlue' exploit, leaked by the Shadow Brokers in 2017, is still being used in attacks today, emphasizing the importance of regular patching.",
    "Privacy coins like Monero and Zcash offer enhanced anonymity compared to Bitcoin, making them a popular choice among cybercriminals.",
    "Data exfiltration can occur through covert channels, such as encoding data in DNS queries, to evade detection by traditional security measures.",
    "The General Data Protection Regulation (GDPR) requires organizations to report data breaches within 72 hours, significantly reducing the time to respond to incidents.",
    "The average cost of a data breach in 2023 was $4.35 million, highlighting the financial impact of inadequate cybersecurity measures.",
    "Cybersecurity mesh is an emerging approach that allows security controls to be placed around individual users or devices, rather than within a network perimeter.",
    "Hackers are increasingly using 'watering hole' attacks, where they compromise websites frequented by their target audience to infect visitors.",
    "Automated bots account for over 40% of all web traffic, with many being malicious and used for activities like scraping, credential stuffing, and DDoS attacks.",
    "Many companies employ 'bug bounty' programs, offering financial rewards to ethical hackers who find and report vulnerabilities in their systems.",
    "Cryptojacking involves unauthorized use of a person's or organization's computing resources to mine cryptocurrency, often causing performance degradation.",
    "Wi-Fi Protected Access 3 (WPA3) is the latest security protocol for wireless networks, offering improved security over its predecessor WPA2.",
    "In 2024, cybercriminals are increasingly targeting supply chain vulnerabilities, exploiting the trust between organizations and their vendors.",
    "Password managers help generate and store complex passwords, reducing the risk of password reuse and weak passwords.",
    "The 'internet of behaviors' (IoB) combines data from the IoT, facial recognition, and other sources to monitor human behavior, raising privacy concerns.",
    "Credential stuffing tools, like Sentry MBA and Snipr, are widely used by attackers to automate the process of testing large numbers of stolen credentials.",
    "The 'Zero Trust' model assumes that every user and device is a potential threat, requiring strict verification and access controls.",
    "Business Email Compromise (BEC) attacks involve impersonating a company executive to trick employees into transferring funds or disclosing sensitive information.",
    "The 'kill chain' framework helps security professionals understand the stages of a cyber attack, from reconnaissance to exfiltration.",
    "Browser fingerprinting is a technique used to track users online by collecting information about their browser and device configurations.",
    "Quantum Key Distribution (QKD) uses the principles of quantum mechanics to create secure communication channels that are theoretically immune to eavesdropping.",
    "Secure Boot is a feature that prevents malicious software and unauthorized operating systems from loading during the startup process.",
    "DNS tunneling is a method attackers use to exfiltrate data by encoding it into DNS queries and responses, bypassing firewalls.",
    "Only about 5% of companies' folders are properly protected, leaving a large amount of sensitive data vulnerable to unauthorized access.",
    "API security is crucial as APIs are increasingly targeted by attackers to gain unauthorized access to data and services.",
    "The Cybersecurity and Infrastructure Security Agency (CISA) regularly provides alerts and guidance on emerging threats and vulnerabilities.",
    "In 2023, there was a surge in attacks targeting remote work infrastructure, like VPNs and collaboration tools, due to the rise in remote working.",
    "The MITRE ATT&CK framework is a widely adopted knowledge base of adversary tactics and techniques used by security professionals to understand and defend against cyber threats.",
    "Honeytokens are decoy data placed within systems to detect unauthorized access and gather intelligence on attackers.",
    "Steganography is the practice of hiding data within other data, such as embedding a hidden message in an image file, to evade detection.",
    "Machine learning is being used to detect anomalies in network traffic, helping to identify potential security incidents in real-time.",
    "Firmware attacks target the software embedded in hardware devices, which is often overlooked in security strategies.",
    "Next-Generation Firewalls (NGFW) provide deeper inspection capabilities than traditional firewalls, including application-level monitoring and intrusion prevention.",
    "Exploit kits are automated tools used by attackers to scan for and exploit vulnerabilities in systems, often delivered through malicious websites.",
    "Heuristic analysis in antivirus software helps detect unknown malware by examining behaviors and characteristics rather than relying solely on signature databases.",
    "The 'BlueKeep' vulnerability in Windows' Remote Desktop Protocol (RDP) allows attackers to execute arbitrary code on a target machine, stressing the importance of network segmentation.",
    "Email security solutions, such as DMARC, SPF, and DKIM, help protect against email spoofing and phishing attacks.",
    "Social media accounts are increasingly being targeted for takeover attacks, often used to spread misinformation or launch further attacks.",
    "In 2024, the demand for cybersecurity professionals continues to outpace supply, resulting in a global shortage of skilled cybersecurity experts.",
    "Remote Desktop Protocol (RDP) brute force attacks have risen significantly, as cybercriminals target poorly secured remote access services.",
    "Cybersecurity awareness training is one of the most effective ways to reduce the risk of social engineering and phishing attacks.",
]


@home_bp.route("/")
@home_bp.route("/home")
def home():
    # Fetch CVE data
    cyber = CyberCVEFetcher()
    cve_data = cyber.get_CVE()

    tips = TeaTimeTips
    tip_of_the_table = random.choice(tips)

    # Limit the number of CVEs to display and shorten the description
    cve_data_short = [
        {
            "title": item["title"],
            "link": item["link"],
            "desc": (
                item["desc"][:100] + "..." if len(item["desc"]) > 100 else item["desc"]
            ),
            "severity": item["severity"],
            "severity_class": item["severity_class"],
        }
        for item in cve_data[:10]
    ]  # Limit to the first 10 CVEs
    return render_template(
        "home.html",
        title="Home",
        cve_items=cve_data_short,
        tip_of_the_table=tip_of_the_table,
    )
